package com.gymmind.workout.application;
import com.gymmind.audit.application.AuditRecorder; import com.gymmind.audit.domain.*; import com.gymmind.coach.application.CoachAssignmentService; import com.gymmind.exercise.domain.repository.ExerciseRepository; import com.gymmind.iam.domain.model.RoleCode; import com.gymmind.member.domain.repository.MemberRepository; import com.gymmind.shared.error.*; import com.gymmind.shared.security.CurrentActor; import com.gymmind.workout.domain.model.*; import com.gymmind.workout.domain.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.Map;
@Service public class DefaultWorkoutPlanService implements WorkoutPlanService { private final WorkoutPlanRepository plans; private final WorkoutPlanItemRepository items; private final ExerciseRepository exercises; private final MemberRepository members; private final CoachAssignmentService assignments; private final AuditRecorder audit; private final WorkoutPlanValidator validator = new WorkoutPlanValidator();
 public DefaultWorkoutPlanService(WorkoutPlanRepository p,WorkoutPlanItemRepository i,ExerciseRepository e,MemberRepository m,CoachAssignmentService a,AuditRecorder audit){plans=p;items=i;exercises=e;members=m;assignments=a;this.audit=audit;}
 @Override @Transactional public WorkoutPlanView create(CurrentActor actor,CreateWorkoutPlanCommand c){require(actor);validator.validate(c);if(c.tenantId()!=null&&!actor.tenantId().equals(c.tenantId()))throw new BusinessException(ErrorCode.FORBIDDEN);members.findByTenantIdAndId(actor.tenantId(),c.memberId()).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));if(!assignments.canAccess(actor,c.memberId()))throw new BusinessException(ErrorCode.FORBIDDEN);for(var i:c.items())exercises.findByTenantIdAndId(actor.tenantId(),i.exerciseId()).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));WorkoutPlan p=plans.save(WorkoutPlan.create(actor.tenantId(),c.memberId(),c.coachId(),c.name(),c.goal(),c.startDate(),c.endDate(),c.description()));for(var i:c.items())items.save(WorkoutPlanItem.create(p,i.exerciseId(),i.dayOfWeek(),i.sets(),i.reps(),i.restSeconds(),i.weight(),i.notes()));audit.record(new AuditEvent("WORKOUT_PLAN_CREATED","WORKOUT_PLAN",p.getId(),AuditResult.SUCCESS,"workout-plan-service",Map.of("resourceName",p.getName())));return WorkoutPlanView.from(p);}
 @Override @Transactional public WorkoutPlanView saveValidatedDraft(CurrentActor actor,CreateWorkoutPlanCommand c){return create(actor,c);}
 @Override @Transactional(readOnly=true) public WorkoutPlanView find(CurrentActor actor,Long id){require(actor);WorkoutPlan p=plans.findByTenantIdAndId(actor.tenantId(),id).orElseThrow(()->new BusinessException(ErrorCode.RESOURCE_NOT_FOUND));if(!assignments.canAccess(actor,p.getMemberId()))throw new BusinessException(ErrorCode.FORBIDDEN);return WorkoutPlanView.from(p);}
 private static void require(CurrentActor a){if(a==null||a.tenantId()==null||(!a.roles().contains(RoleCode.GYM_ADMIN)&&!a.roles().contains(RoleCode.COACH))||!a.hasPermission("workout:write"))throw new BusinessException(ErrorCode.FORBIDDEN);}
}
